import type { FootballData, Match, Player, Standing } from "./types";

export const matches: Match[] = [
  {
    id: "m1",
    opponent: "Kocaelispor",
    organization: "lig",
    competition: "Trendyol Süper Lig",
    date: "2026-08-16T19:00:00+03:00",
    venue: "Tüpraş Stadyumu",
    home: true,
    status: "finished",
    score: { besiktas: 2, opponent: 0 },
  },
  {
    id: "m2",
    opponent: "Samsunspor",
    organization: "lig",
    competition: "Trendyol Süper Lig",
    date: "2026-08-23T21:00:00+03:00",
    venue: "Samsun Yeni 19 Mayıs Stadyumu",
    home: false,
    status: "finished",
    score: { besiktas: 1, opponent: 1 },
  },
  {
    id: "m3",
    opponent: "Rapid Wien",
    organization: "avrupa",
    competition: "UEFA Avrupa Ligi",
    date: "2026-08-27T20:00:00+03:00",
    venue: "Tüpraş Stadyumu",
    home: true,
    status: "finished",
    score: { besiktas: 3, opponent: 1 },
  },
  {
    id: "m4",
    opponent: "Göztepe",
    organization: "lig",
    competition: "Trendyol Süper Lig",
    date: "2026-09-13T20:00:00+03:00",
    venue: "Gürsel Aksel Stadyumu",
    home: false,
    status: "scheduled",
  },
  {
    id: "m5",
    opponent: "Roma",
    organization: "avrupa",
    competition: "UEFA Avrupa Ligi",
    date: "2026-09-17T22:00:00+03:00",
    venue: "Tüpraş Stadyumu",
    home: true,
    status: "scheduled",
  },
  {
    id: "m6",
    opponent: "Antalyaspor",
    organization: "lig",
    competition: "Trendyol Süper Lig",
    date: "2026-09-20T19:00:00+03:00",
    venue: "Tüpraş Stadyumu",
    home: true,
    status: "scheduled",
  },
  {
    id: "m7",
    opponent: "Trabzonspor",
    organization: "lig",
    competition: "Trendyol Süper Lig",
    date: "2026-10-04T00:00:00+03:00",
    venue: "Papara Park",
    home: false,
    status: "tbd",
  },
  {
    id: "m8",
    opponent: "Konyaspor",
    organization: "kupa",
    competition: "Ziraat Türkiye Kupası",
    date: "2026-12-16T20:30:00+03:00",
    venue: "Tüpraş Stadyumu",
    home: true,
    status: "scheduled",
  },
  {
    id: "m9",
    opponent: "Alanyaspor",
    organization: "kupa",
    competition: "Ziraat Türkiye Kupası",
    date: "2027-01-13T00:00:00+03:00",
    venue: "Oba Stadyumu",
    home: false,
    status: "tbd",
  },
];

export const standings: Standing[] = [
  {
    position: 1,
    team: "Galatasaray",
    played: 4,
    won: 4,
    drawn: 0,
    lost: 0,
    goalsFor: 11,
    goalsAgainst: 2,
    points: 12,
  },
  {
    position: 2,
    team: "Beşiktaş",
    played: 4,
    won: 3,
    drawn: 1,
    lost: 0,
    goalsFor: 9,
    goalsAgainst: 3,
    points: 10,
  },
  {
    position: 3,
    team: "Fenerbahçe",
    played: 4,
    won: 3,
    drawn: 0,
    lost: 1,
    goalsFor: 8,
    goalsAgainst: 4,
    points: 9,
  },
  {
    position: 4,
    team: "Trabzonspor",
    played: 4,
    won: 2,
    drawn: 1,
    lost: 1,
    goalsFor: 6,
    goalsAgainst: 4,
    points: 7,
  },
  {
    position: 5,
    team: "Samsunspor",
    played: 4,
    won: 2,
    drawn: 1,
    lost: 1,
    goalsFor: 5,
    goalsAgainst: 4,
    points: 7,
  },
];

export const players: Player[] = [
  {
    id: "p1",
    name: "Mert Günok",
    number: 34,
    position: "Kaleci",
    birthDate: "1989-03-01",
    nationality: "Türkiye",
    appearances: 4,
    starts: 4,
    minutes: 360,
    goals: 0,
    assists: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p2",
    name: "Ersin Destanoğlu",
    number: 30,
    position: "Kaleci",
    birthDate: "2001-01-01",
    nationality: "Türkiye",
    appearances: 1,
    starts: 0,
    minutes: 25,
    goals: 0,
    assists: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p3",
    name: "Emirhan Topçu",
    number: 53,
    position: "Defans",
    birthDate: "2000-10-11",
    nationality: "Türkiye",
    appearances: 4,
    starts: 4,
    minutes: 348,
    goals: 1,
    assists: 0,
    yellowCards: 1,
    redCards: 0,
  },
  {
    id: "p4",
    name: "Gabriel Paulista",
    number: 3,
    position: "Defans",
    birthDate: "1990-11-26",
    nationality: "Brezilya",
    appearances: 3,
    starts: 3,
    minutes: 270,
    goals: 0,
    assists: 0,
    yellowCards: 1,
    redCards: 0,
  },
  {
    id: "p5",
    name: "Rafa Silva",
    number: 27,
    position: "Orta saha",
    birthDate: "1993-05-17",
    nationality: "Portekiz",
    appearances: 4,
    starts: 4,
    minutes: 352,
    goals: 2,
    assists: 2,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p6",
    name: "Gedson Fernandes",
    number: 83,
    position: "Orta saha",
    birthDate: "1999-01-09",
    nationality: "Portekiz",
    appearances: 4,
    starts: 4,
    minutes: 360,
    goals: 1,
    assists: 1,
    yellowCards: 2,
    redCards: 0,
  },
  {
    id: "p7",
    name: "Demir Ege Tıknaz",
    number: 6,
    position: "Orta saha",
    birthDate: "2004-08-17",
    nationality: "Türkiye",
    appearances: 3,
    starts: 1,
    minutes: 138,
    goals: null,
    assists: null,
    yellowCards: 1,
    redCards: 0,
  },
  {
    id: "p8",
    name: "Semih Kılıçsoy",
    number: 9,
    position: "Forvet",
    birthDate: "2005-08-15",
    nationality: "Türkiye",
    appearances: 4,
    starts: 3,
    minutes: 289,
    goals: 3,
    assists: 1,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p9",
    name: "Mustafa Hekimoğlu",
    number: 91,
    position: "Forvet",
    birthDate: "2007-04-22",
    nationality: "Türkiye",
    appearances: 2,
    starts: 0,
    minutes: null,
    goals: 1,
    assists: null,
    yellowCards: 0,
    redCards: 0,
  },
];

export const demoData: FootballData = {
  source: "demo",
  updatedAt: "2026-08-28T10:30:00+03:00",
  stale: false,
  matches,
  standings,
  players,
};
