import type { FootballData, Match, Player, Standing } from "./types";

export const matches: Match[] = [
  {
    id: "m1",
    opponent: "Eyüpspor",
    organization: "lig",
    competition: "Trendyol Süper Lig",
    date: "2026-08-16T21:30:00+03:00",
    venue: "Tüpraş Stadyumu",
    home: true,
    status: "finished",
    score: { besiktas: 1, opponent: 0 },
  },
  {
    id: "m2",
    opponent: "Alanyaspor",
    organization: "lig",
    competition: "Trendyol Süper Lig",
    date: "2026-08-23T21:30:00+03:00",
    venue: "Alanya Oba Stadyumu",
    home: false,
    status: "finished",
    score: { besiktas: 0, opponent: 1 },
  },
  {
    id: "m3",
    opponent: "Çorum FK",
    organization: "lig",
    competition: "Trendyol Süper Lig",
    date: "2026-08-31T21:30:00+03:00",
    venue: "Tüpraş Stadyumu",
    home: true,
    status: "scheduled",
  },
  {
    id: "m4",
    opponent: "Fenerbahçe",
    organization: "lig",
    competition: "Trendyol Süper Lig",
    date: "2026-09-06T00:00:00+03:00",
    venue: "Şükrü Saracoğlu Stadyumu",
    home: false,
    status: "tbd",
  },
  {
    id: "m5",
    opponent: "Erzurumspor FK",
    organization: "lig",
    competition: "Trendyol Süper Lig",
    date: "2026-09-13T00:00:00+03:00",
    venue: "Tüpraş Stadyumu",
    home: true,
    status: "tbd",
  },
  {
    id: "m6",
    opponent: "Amed SK",
    organization: "lig",
    competition: "Trendyol Süper Lig",
    date: "2026-09-20T00:00:00+03:00",
    venue: "Diyarbakır Stadyumu",
    home: false,
    status: "tbd",
  },
  {
    id: "m7",
    opponent: "Kocaelispor",
    organization: "lig",
    competition: "Trendyol Süper Lig",
    date: "2026-10-11T00:00:00+03:00",
    venue: "Tüpraş Stadyumu",
    home: true,
    status: "tbd",
  },
  {
    id: "m8",
    opponent: "Trabzonspor",
    organization: "lig",
    competition: "Trendyol Süper Lig",
    date: "2026-10-18T00:00:00+03:00",
    venue: "Papara Park",
    home: false,
    status: "tbd",
  },
  {
    id: "m9",
    opponent: "Başakşehir",
    organization: "lig",
    competition: "Trendyol Süper Lig",
    date: "2026-10-25T00:00:00+03:00",
    venue: "Tüpraş Stadyumu",
    home: true,
    status: "tbd",
  },
  {
    id: "m10",
    opponent: "Kasımpaşa",
    organization: "lig",
    competition: "Trendyol Süper Lig",
    date: "2026-11-01T00:00:00+03:00",
    venue: "Recep Tayyip Erdoğan Stadyumu",
    home: false,
    status: "tbd",
  },
  {
    id: "m11",
    opponent: "Gençlerbirliği",
    organization: "lig",
    competition: "Trendyol Süper Lig",
    date: "2026-11-08T00:00:00+03:00",
    venue: "Tüpraş Stadyumu",
    home: true,
    status: "tbd",
  },
  {
    id: "m12",
    opponent: "Konyaspor",
    organization: "lig",
    competition: "Trendyol Süper Lig",
    date: "2026-11-22T00:00:00+03:00",
    venue: "Konya Büyükşehir Stadyumu",
    home: false,
    status: "tbd",
  },
  {
    id: "m13",
    opponent: "Galatasaray",
    organization: "lig",
    competition: "Trendyol Süper Lig",
    date: "2026-11-29T00:00:00+03:00",
    venue: "Tüpraş Stadyumu",
    home: true,
    status: "tbd",
  },
  {
    id: "m14",
    opponent: "Samsunspor",
    organization: "lig",
    competition: "Trendyol Süper Lig",
    date: "2026-12-06T00:00:00+03:00",
    venue: "Tüpraş Stadyumu",
    home: true,
    status: "tbd",
  },
  {
    id: "m15",
    opponent: "Gaziantep FK",
    organization: "lig",
    competition: "Trendyol Süper Lig",
    date: "2026-12-13T00:00:00+03:00",
    venue: "Gaziantep Stadyumu",
    home: false,
    status: "tbd",
  },
  {
    id: "m16",
    opponent: "Çaykur Rizespor",
    organization: "lig",
    competition: "Trendyol Süper Lig",
    date: "2026-12-20T00:00:00+03:00",
    venue: "Tüpraş Stadyumu",
    home: true,
    status: "tbd",
  },
  {
    id: "m17",
    opponent: "Göztepe",
    organization: "lig",
    competition: "Trendyol Süper Lig",
    date: "2027-01-17T00:00:00+03:00",
    venue: "Gürsel Aksel Stadyumu",
    home: false,
    status: "tbd",
  },
  {
    id: "e1",
    opponent: "UEFA rakibi",
    organization: "avrupa",
    competition: "UEFA organizasyonu",
    date: "2026-09-24T00:00:00+03:00",
    venue: "Belirlenecek",
    home: true,
    status: "tbd",
  },
  {
    id: "c1",
    opponent: "Konyaspor",
    organization: "kupa",
    competition: "Ziraat Türkiye Kupası",
    date: "2026-12-16T20:30:00+03:00",
    venue: "Tüpraş Stadyumu",
    home: true,
    status: "scheduled",
  },
];

export const standings: Standing[] = [
  [1, "Gençlerbirliği", 2, 2, 0, 0, 3, 1, 6],
  [2, "Galatasaray", 2, 1, 1, 0, 6, 2, 4],
  [3, "Samsunspor", 2, 1, 1, 0, 5, 3, 4],
  [4, "Trabzonspor", 2, 1, 1, 0, 3, 2, 4],
  [5, "Alanyaspor", 2, 1, 1, 0, 2, 1, 4],
  [6, "Gaziantep FK", 2, 1, 1, 0, 2, 1, 4],
  [7, "Kasımpaşa", 2, 1, 1, 0, 2, 1, 4],
  [8, "Fenerbahçe", 2, 1, 0, 1, 5, 4, 3],
  [9, "Amed SK", 2, 1, 0, 1, 3, 2, 3],
  [10, "Başakşehir", 2, 1, 0, 1, 3, 2, 3],
  [11, "Kocaelispor", 2, 1, 0, 1, 2, 2, 3],
  [12, "Beşiktaş", 2, 1, 0, 1, 1, 1, 3],
  [13, "Çaykur Rizespor", 2, 1, 0, 1, 1, 2, 3],
  [14, "Göztepe", 2, 0, 1, 1, 3, 4, 1],
  [15, "Çorum FK", 2, 0, 1, 1, 2, 3, 1],
  [16, "Eyüpspor", 2, 0, 0, 2, 0, 2, 0],
].map(
  ([
    position,
    team,
    played,
    won,
    drawn,
    lost,
    goalsFor,
    goalsAgainst,
    points,
  ]) => ({
    position,
    team,
    played,
    won,
    drawn,
    lost,
    goalsFor,
    goalsAgainst,
    points,
  }),
) as Standing[];

export const players: Player[] = [
  {
    id: "p1",
    name: "Mert Günok",
    number: 34,
    position: "Kaleci",
    birthDate: "1989-03-01",
    nationality: "Türkiye",
    appearances: 2,
    starts: 2,
    minutes: 180,
    goals: 0,
    assists: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p2",
    name: "Ersin Destanoğlu",
    number: 30,
    position: "Kaleci",
    birthDate: "2001-01-01",
    nationality: "Türkiye",
    appearances: 0,
    starts: 0,
    minutes: 0,
    goals: 0,
    assists: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p3",
    name: "Emirhan Topçu",
    number: 53,
    position: "Defans",
    birthDate: "2000-10-11",
    nationality: "Türkiye",
    appearances: 2,
    starts: 2,
    minutes: 180,
    goals: 0,
    assists: 0,
    yellowCards: 1,
    redCards: 0,
  },
  {
    id: "p4",
    name: "Gabriel Paulista",
    number: 3,
    position: "Defans",
    birthDate: "1990-11-26",
    nationality: "Brezilya",
    appearances: 2,
    starts: 2,
    minutes: 180,
    goals: 0,
    assists: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p5",
    name: "Rafa Silva",
    number: 27,
    position: "Orta saha",
    birthDate: "1993-05-17",
    nationality: "Portekiz",
    appearances: 2,
    starts: 2,
    minutes: 176,
    goals: 0,
    assists: 1,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p6",
    name: "Gedson Fernandes",
    number: 83,
    position: "Orta saha",
    birthDate: "1999-01-09",
    nationality: "Portekiz",
    appearances: 2,
    starts: 2,
    minutes: 180,
    goals: 0,
    assists: 0,
    yellowCards: 1,
    redCards: 0,
  },
  {
    id: "p7",
    name: "Demir Ege Tıknaz",
    number: 6,
    position: "Orta saha",
    birthDate: "2004-08-17",
    nationality: "Türkiye",
    appearances: 2,
    starts: 1,
    minutes: 101,
    goals: null,
    assists: null,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p8",
    name: "Semih Kılıçsoy",
    number: 9,
    position: "Forvet",
    birthDate: "2005-08-15",
    nationality: "Türkiye",
    appearances: 2,
    starts: 2,
    minutes: 165,
    goals: 1,
    assists: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p9",
    name: "Mustafa Hekimoğlu",
    number: 91,
    position: "Forvet",
    birthDate: "2007-04-22",
    nationality: "Türkiye",
    appearances: 1,
    starts: 0,
    minutes: null,
    goals: null,
    assists: null,
    yellowCards: 0,
    redCards: 0,
  },
];

export const demoData: FootballData = {
  source: "demo",
  updatedAt: "2026-08-28T15:15:00+03:00",
  stale: false,
  matches,
  standings,
  players,
};
